In [1]:
import numpy as np

In [2]:
G=np.zeros( (6,6), dtype=np.int8)
NODES=['u','v','w','x','y','z']
nodecount = len(NODES)
u,v,w,x,y,z=0,1,2,3,4,5

In [3]:
def add_edge(graph,node1,node2,weight):
    graph[node1,node2]=graph[node2,node1]=weight
add_edge(G,u,v,2)
add_edge(G,u,x,1)
add_edge(G,u,w,5)
add_edge(G,x,v,2)
add_edge(G,x,w,3)
add_edge(G,x,y,1)
add_edge(G,w,v,3)
add_edge(G,w,y,1)
add_edge(G,w,z,5)
add_edge(G,y,z,2)

In [4]:
print("Node count:",len(G))
print("Edge count:",np.count_nonzero(G)//2)
print(G)

Node count: 6
Edge count: 10
[[0 2 5 1 0 0]
 [2 0 3 2 0 0]
 [5 3 0 3 1 5]
 [1 2 3 0 1 0]
 [0 0 1 1 0 2]
 [0 0 5 0 2 0]]


In [49]:
def list_paths_from(graph,this_path,all_paths):
    this_node=this_path[-1]
    for i in range(0,len(graph)):
        if i not in this_path: # avoid cycles
            if graph[this_node,i]>0: # positive weight => adjacency
                next_path = this_path.copy()
                next_path.append(i)
                #print("this_path",this_path)
                #print("next_path",next_path)
                all_paths.append(next_path)
                all_paths = list_paths_from(graph,next_path,all_paths)
    return all_paths
def get_path_name(one_path):
    pname=''
    for i in one_path:
        pname = pname + NODES[i]
    return pname
def show_all_paths(paths):
    for p in paths:
        print(get_path_name(p))

In [50]:
paths_from_U = [[u]]
paths_from_U = list_paths_from(G,[u],paths_from_U)
show_all_paths(paths_from_U)

u
uv
uvw
uvwx
uvwxy
uvwxyz
uvwy
uvwyx
uvwyz
uvwz
uvwzy
uvwzyx
uvx
uvxw
uvxwy
uvxwyz
uvxwz
uvxwzy
uvxy
uvxyw
uvxywz
uvxyz
uvxyzw
uw
uwv
uwvx
uwvxy
uwvxyz
uwx
uwxv
uwxy
uwxyz
uwy
uwyx
uwyxv
uwyz
uwz
uwzy
uwzyx
uwzyxv
ux
uxv
uxvw
uxvwy
uxvwyz
uxvwz
uxvwzy
uxw
uxwv
uxwy
uxwyz
uxwz
uxwzy
uxy
uxyw
uxywv
uxywz
uxyz
uxyzw
uxyzwv
