# Graph
Listing all paths from source to sink in an undirected weighted graph.  
Jason Miller.  

In [1]:
import numpy as np

## Define the Graph
Represent the graph on page 377, Fig 5.3, of Kurose & Ross 7th ed.

In [2]:
G=np.zeros( (6,6), dtype=np.int8)
NODES=['u','v','w','x','y','z']
nodecount = len(NODES)
u,v,w,x,y,z=0,1,2,3,4,5

In [3]:
def add_edge(graph,node1,node2,weight):
    graph[node1,node2]=graph[node2,node1]=weight
add_edge(G,u,v,2)
add_edge(G,u,x,1)
add_edge(G,u,w,5)
add_edge(G,x,v,2)
add_edge(G,x,w,3)
add_edge(G,x,y,1)
add_edge(G,w,v,3)
add_edge(G,w,y,1)
add_edge(G,w,z,5)
add_edge(G,y,z,2)

In [4]:
print("Node count:",len(G))
print("Edge count:",np.count_nonzero(G)//2)
print(G)

Node count: 6
Edge count: 10
[[0 2 5 1 0 0]
 [2 0 3 2 0 0]
 [5 3 0 3 1 5]
 [1 2 3 0 1 0]
 [0 0 1 1 0 2]
 [0 0 5 0 2 0]]


## Graph utility functions

In [5]:
def list_paths_from(graph,this_path,all_paths):
    this_node=this_path[-1]
    for i in range(0,len(graph)):
        if i not in this_path: # avoid cycles
            if graph[this_node,i]>0: # positive weight => adjacency
                next_path = this_path.copy()
                next_path.append(i)
                #print("this_path",this_path)
                #print("next_path",next_path)
                all_paths.append(next_path)
                all_paths = list_paths_from(graph,next_path,all_paths)
    return all_paths
def get_path_name(one_path):
    pname=''
    for i in one_path:
        pname = pname + NODES[i]
    return pname
def show_all_paths(paths):
    c = 0
    for p in paths:
        c = c+1
        print(c,get_path_name(p))
def list_paths_a_to_b(graph,a,b):
    paths_from_a = [[a]]
    paths_from_a = list_paths_from(G,[a],paths_from_a)
    paths_a_to_b = []
    for p in paths_from_a:
        if p[-1]==b:
            paths_a_to_b.append(p)
    show_all_paths(paths_a_to_b)

## Graph exploration 

In [6]:
# Long output, was used for debugging
paths_from_Y = [[y]]
paths_from_Y = list_paths_from(G,[y],paths_from_Y)
# show_all_paths(paths_from_Y)

In [7]:
list_paths_a_to_b(G,y,u)

1 ywu
2 ywvu
3 ywvxu
4 ywxu
5 ywxvu
6 yxu
7 yxvu
8 yxvwu
9 yxwu
10 yxwvu
11 yzwu
12 yzwvu
13 yzwvxu
14 yzwxu
15 yzwxvu


In [8]:
list_paths_a_to_b(G,x,z)

1 xuvwyz
2 xuvwz
3 xuwyz
4 xuwz
5 xvuwyz
6 xvuwz
7 xvwyz
8 xvwz
9 xwyz
10 xwz
11 xywz
12 xyz


In [9]:
list_paths_a_to_b(G,z,u)

1 zwu
2 zwvu
3 zwvxu
4 zwxu
5 zwxvu
6 zwyxu
7 zwyxvu
8 zywu
9 zywvu
10 zywvxu
11 zywxu
12 zywxvu
13 zyxu
14 zyxvu
15 zyxvwu
16 zyxwu
17 zyxwvu


In [10]:
list_paths_a_to_b(G,z,w)

1 zw
2 zyw
3 zyxuvw
4 zyxuw
5 zyxvuw
6 zyxvw
7 zyxw
