In [1]:
import numpy as np

In [2]:
G=np.zeros( (6,6), dtype=np.int8)
NODES=['u','v','w','x','y','z']
nodecount = len(NODES)
u,v,w,x,y,z=0,1,2,3,4,5

In [3]:
def add_edge(graph,node1,node2,weight):
    graph[node1,node2]=graph[node2,node1]=weight
add_edge(G,u,v,2)
add_edge(G,u,x,1)
add_edge(G,u,w,5)
add_edge(G,x,v,2)
add_edge(G,x,w,3)
add_edge(G,x,y,1)
add_edge(G,w,v,3)
add_edge(G,w,y,1)
add_edge(G,w,z,5)
add_edge(G,y,z,2)

In [4]:
print("Node count:",len(G))
print("Edge count:",np.count_nonzero(G)//2)
print(G)

Node count: 6
Edge count: 10
[[0 2 5 1 0 0]
 [2 0 3 2 0 0]
 [5 3 0 3 1 5]
 [1 2 3 0 1 0]
 [0 0 1 1 0 2]
 [0 0 5 0 2 0]]


In [7]:
def list_paths_from(graph,node,exclude):
    for i in range(0,nodecount):
        if i!=node:
            if graph[node,i]>0:
                if i not in exclude:
                    exclude.append(i)
    return exclude
def show_path_name(intlist):
    name=''
    for i in intlist:
        name = name + NODES[i]
    return name

In [9]:
U = list_paths_from(G,u,[])
NU = show_path_name(U)
print(NU)

vwx
